vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        articles_images:
            uri_prefix: /images/articles_images
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
